In [1]:
data_path1 = "data/blood/biased_leukemia_dataset.csv"
data_path2 = "data/blood/The_Cancer_data_1500_V2.csv"

In [9]:
import pandas as pd

df1 = pd.read_csv("data/blood/biased_leukemia_dataset.csv")
df2 = pd.read_csv(data_path2)
df1.head()

,Patient_ID,Age,Gender,Country,WBC_Count,RBC_Count,Platelet_Count,Hemoglobin_Level,Bone_Marrow_Blasts,Genetic_Mutation,...,Alcohol_Consumption,Radiation_Exposure,Infection_History,BMI,Chronic_Illness,Immune_Disorders,Ethnicity,Socioeconomic_Status,Urban_Rural,Leukemia_Status
0,1,52,Male,China,2698,5.36,262493,12.2,72,Yes,...,No,No,No,24.0,No,No,Ethnic_Group_B,Low,Rural,Negative
1,2,15,Female,China,4857,4.81,277877,11.9,97,Yes,...,No,No,No,28.7,No,No,Ethnic_Group_A,Low,Urban,Positive
2,3,72,Male,France,9614,5.17,319600,13.4,94,No,...,Yes,No,No,27.7,No,No,Ethnic_Group_B,Low,Urban,Negative
3,4,61,Male,Brazil,6278,5.41,215200,11.6,50,No,...,No,No,No,31.6,No,No,Ethnic_Group_A,Medium,Rural,Negative
4,5,21,Male,Brazil,8342,4.78,309169,14.3,28,No,...,No,No,No,22.3,No,No,Ethnic_Group_B,Low,Rural,Negative

In [12]:
print("Gender:", df1['Gender'].unique())
print("Smoking_Status:", df1['Smoking_Status'].unique())
print("Genetic_Mutation:", df1['Genetic_Mutation'].unique())
print("Family_History:", df1['Family_History'].unique())
print("Radiation_Exposure:", df1['Radiation_Exposure'].unique())
print("Infection_History:", df1['Infection_History'].unique())
print("Leukemia_Status:", df1['Leukemia_Status'].unique())

df1['Gender'] = df1['Gender'].map({'Male': 1, 'Female': 0}).fillna(df1['Gender'])
df1['Smoking_Status'] = df1['Smoking_Status'].map({'Yes': 1, 'No': 0}).fillna(0)  # Default to 0 if unknown
df1['Genetic_Mutation'] = df1['Genetic_Mutation'].map({'Yes': 1, 'No': 0}).fillna(0)
df1['Family_History'] = df1['Family_History'].map({'Yes': 1, 'No': 0}).fillna(0)
df1['Radiation_Exposure'] = df1['Radiation_Exposure'].map({'Yes': 1, 'No': 0}).fillna(0)
df1['Infection_History'] = df1['Infection_History'].map({'Yes': 1, 'No': 0}).fillna(0)
df1['Leukemia_Status'] = df1['Leukemia_Status'].map({'Positive': 1, 'Negative': 0}).fillna(0)

Gender: ['Male' 'Female']
Smoking_Status: ['Yes' 'No']
Genetic_Mutation: ['Yes' 'No']
Family_History: ['No' 'Yes']
Radiation_Exposure: ['No' 'Yes']
Infection_History: ['No' 'Yes']
Leukemia_Status: ['Negative' 'Positive']

In [13]:
df1.head()

,Patient_ID,Age,Gender,Country,WBC_Count,RBC_Count,Platelet_Count,Hemoglobin_Level,Bone_Marrow_Blasts,Genetic_Mutation,...,Alcohol_Consumption,Radiation_Exposure,Infection_History,BMI,Chronic_Illness,Immune_Disorders,Ethnicity,Socioeconomic_Status,Urban_Rural,Leukemia_Status
0,1,52,1,China,2698,5.36,262493,12.2,72,1,...,No,0,0,24.0,No,No,Ethnic_Group_B,Low,Rural,0
1,2,15,0,China,4857,4.81,277877,11.9,97,1,...,No,0,0,28.7,No,No,Ethnic_Group_A,Low,Urban,1
2,3,72,1,France,9614,5.17,319600,13.4,94,0,...,Yes,0,0,27.7,No,No,Ethnic_Group_B,Low,Urban,0
3,4,61,1,Brazil,6278,5.41,215200,11.6,50,0,...,No,0,0,31.6,No,No,Ethnic_Group_A,Medium,Rural,0
4,5,21,1,Brazil,8342,4.78,309169,14.3,28,0,...,No,0,0,22.3,No,No,Ethnic_Group_B,Low,Rural,0

In [14]:
selected_columns = [
    'Age',
    'Gender',
    'WBC_Count',
    'RBC_Count',
    'Platelet_Count',
    'Hemoglobin_Level',
    'Bone_Marrow_Blasts',
    'Family_History',
    'Smoking_Status',
    'Radiation_Exposure',
    # 'Chronic_Illness',
    # 'Immune_Disorders',
    'BMI',
    'Infection_History'
]
df = df1[selected_columns]
out = df1['Leukemia_Status']
df.head()

,Age,Gender,WBC_Count,RBC_Count,Platelet_Count,Hemoglobin_Level,Bone_Marrow_Blasts,Family_History,Smoking_Status,Radiation_Exposure,BMI,Infection_History
0,52,1,2698,5.36,262493,12.2,72,0,1,0,24.0,0
1,15,0,4857,4.81,277877,11.9,97,0,0,0,28.7,0
2,72,1,9614,5.17,319600,13.4,94,1,0,0,27.7,0
3,61,1,6278,5.41,215200,11.6,50,0,1,0,31.6,0
4,21,1,8342,4.78,309169,14.3,28,0,1,0,22.3,0

In [15]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np

In [16]:
# Assuming you have your features in X and target in y
# X, y = load_your_data() 

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(df, out, test_size=0.2)

In [17]:
# For Classification
rf_model_clf = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model_clf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [18]:
# Make predictions on the test set
y_pred = rf_model_clf.predict(X_test)

# Evaluate the model (e.g., for classification)
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.4f}")

Model Accuracy: 0.8507

In [21]:
from joblib import dump
import os

# Create the 'model' folder if it doesn't exist
os.makedirs('model', exist_ok=True)

# Save the model to the 'model' folder
dump(rf_model_clf, 'model/random_forest_model.joblib')

print("Model saved to 'model/random_forest_model.joblib'")

Model saved to 'model/random_forest_model.joblib'